#!/bin/bash

TODAY=`date +%j`                 # Today, as day-of-year (1-366)
BIRTH=`date -d 16-Mar-2022 +%j`   # Christmas day, in same format
VAR=$(expr $BIRTH - $TODAY + 365) 
echo "There are $VAR days until 答辩."
echo $TODAY
echo $(expr $BIRTH + 365)
